### ISSUE TITLE
Бот залип на циклической попытке отправки поста в канал ТГ

### ISSUE THREAD

**Issue by seligor** [alcortazzo/vktgbot#60]
https://vk.com/wall-164402203_43426

Проблема возникла вот с этим постом. 
В канал ТГ стал постить бесконечно текстовую часть поста с дефолтным засыпанием

```
2023-07-23 22:13:06.654 | INFO     | send_posts:send_text_post:51 - Text post sent to Telegram.
2023-07-23 22:13:06.918 | WARNING  | send_posts:send_post:29 - Bad request. Wait 60 seconds. Try: 1. Failed to send message #1 with the error message "wrong type of the web page content"
2023-07-23 22:14:07.607 | INFO     | send_posts:send_text_post:51 - Text post sent to Telegram.
2023-07-23 22:14:07.834 | WARNING  | send_posts:send_post:29 - Bad request. Wait 60 seconds. Try: 2. Failed to send message #1 with the error message "wrong type of the web page content"
2023-07-23 22:15:08.474 | INFO     | send_posts:send_text_post:51 - Text post sent to Telegram.
2023-07-23 22:15:08.652 | WARNING  | send_posts:send_post:29 - Bad request. Wait 60 seconds. Try: 3. Failed to send message #1 with the error message "wrong type of the web page content"
^C2023-07-23 22:15:10.668 | ERROR    | __main__:<module>:36 - An error has been caught in function '<module>', process 'MainProcess' (53988), thread 'MainThread' (139983913931072):
Traceback (most recent call last):

> File "/home/seligor/scripts/vk_to_tg_bot/MAYAK/vktgbot/__main__.py", line 36, in <module>
    main()
    └ <function main at 0x7f5089894180>

  File "/home/seligor/scripts/vk_to_tg_bot/MAYAK/vktgbot/__main__.py", line 30, in main
    start_script()
    └ <function start_script at 0x7f508a8c3100>

  File "/home/seligor/scripts/vk_to_tg_bot/MAYAK/vktgbot/start_script.py", line 73, in start_script
    executor.start(
    │        └ <function start at 0x7f5089c86660>
    └ <module 'aiogram.utils.executor' from '/home/seligor/scripts/vk_to_tg_bot/MAYAK/.venv/lib/python3.11/site-packages/aiogram/ut...

  File "/home/seligor/scripts/vk_to_tg_bot/MAYAK/.venv/lib/python3.11/site-packages/aiogram/utils/executor.py", line 127, in start
    return executor.start(future)
           │        │     └ <coroutine object send_post at 0x7f5089ae2180>
           │        └ <function Executor.start at 0x7f5089c87060>
           └ <aiogram.utils.executor.Executor object at 0x7f508a8f5d10>
  File "/home/seligor/scripts/vk_to_tg_bot/MAYAK/.venv/lib/python3.11/site-packages/aiogram/utils/executor.py", line 351, in start
    loop.run_until_complete(self._shutdown_polling())
    │    │                  │    └ <function Executor._shutdown_polling at 0x7f5089c87380>
    │    │                  └ <aiogram.utils.executor.Executor object at 0x7f508a8f5d10>
    │    └ <function BaseEventLoop.run_until_complete at 0x7f508a976b60>
    └ <_UnixSelectorEventLoop running=False closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 651, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')

RuntimeError: Event loop stopped before Future completed.

```

**Comment by alcortazzo** [comment]
Мне не удалось повторить ошибку.

Подскажите какую версию бота вьі используете и удается ли повторить ошибку сейчас?
