### ISSUE TITLE
SyntaxError: invalid syntax (doc['size']=)

### ISSUE THREAD

**Issue by echubarov** [alcortazzo/vktgbot#64]
> python vktgbot

```
Traceback (most recent call last):
  File "C:\dev\Python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\dev\Python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "vktgbot\__main__.py", line 14, in <module>
    from start_script import start_script
  File "vktgbot\start_script.py", line 10, in <module>
    from parse_posts import parse_post
  File "<fstring>", line 1
    (doc['size']=)
                ^
SyntaxError: invalid syntax
```

**Comment by echubarov** [comment]
python --version
```
Python 3.7.6
```

**Comment by alcortazzo** [comment]
В обеих актуальньіх ветках ошибок в синтаксисе нет ([master](https://github.com/alcortazzo/vktgbot/blob/master/vktgbot/parse_posts.py#L95C91-L95C103), [v4-dev](https://github.com/alcortazzo/vktgbot/blob/v4-dev/vktgbot/parse_posts.py#L153C8-L153C8)).

f-strings поддерживаются, начиная с 3.6 python.
Значит, скорее всего, у вас локальньіе изменения в коде - проверьте через git diff.

**Comment by echubarov** [comment]
Изменены только `.env` и `last_id.txt`:

❯ git pull
```
warning: redirecting to https://github.com/alcortazzo/vktgbot.git/
Already up to date.
```
❯ git stash pop
```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .env
        modified:   last_id.txt

no changes added to commit (use "git add" and/or "git commit -a")
Dropped refs/stash@{0} (86610dccf1b931e01ac985c385f3fc2a39c11193)
```
❯ git diff
```
diff --git a/.env b/.env     
index 6504232..fc5e273 100644
--- a/.env
+++ b/.env
@@ -3,22 +3,22 @@
 # VAR_TG_CHANNEL = "@durov"
 # VAR_TG_CHANNEL = -1234567890987
 # Don't forget to add bot to this channel as an administrator!
-VAR_TG_CHANNEL = @aaaa
+VAR_TG_CHANNEL = @mytgchannel

 # Token for your Telegram bot.
 # You can get it here: https://t.me/BotFather
-VAR_TG_BOT_TOKEN = 1234567890:AAA-AaA1aaa1AAaaAa1a1AAAAA-a1aa1-Aa
+VAR_TG_BOT_TOKEN = mybottoken

 # Personal token for your VK profile.
 # You can get it here:
 # https://github.com/alcortazzo/vktgbot/wiki/How-to-get-personal-access-token
-VAR_VK_TOKEN = 00a0a0ab00f0a0ab00f0a6ab0c00000b0f000f000f0a0ab0a00b000000dd00000000de0
+VAR_VK_TOKEN = myvktoken

 # Part of the link (after vk.com/) to the VK channel
 # for example:
 # if link is vk.com/>>>example<<<
 # VAR_VK_DOMAIN = "example"
-VAR_VK_DOMAIN = bbbb
+VAR_VK_DOMAIN = vkgroup

 # Version of VK API (https://vk.com/dev/versions).
 # Used for "wall.get" method
diff --git a/last_id.txt b/last_id.txt
index 573541a..2c83102 100644
--- a/last_id.txt
+++ b/last_id.txt
@@ -1 +1 @@
-0
+1934504
```
❯ python vktgbot
```
Traceback (most recent call last):
  File "C:\dev\Python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\dev\Python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "vktgbot\__main__.py", line 14, in <module>
    from start_script import start_script
  File "vktgbot\start_script.py", line 10, in <module>
    from parse_posts import parse_post
  File "<fstring>", line 1
    (doc['size']=)
                ^
SyntaxError: invalid syntax
```

**Comment by alcortazzo** [comment]
А, разобрался. F-strings в Python появились в 3.6, но такой синтаксис появился только в 3.8 ([docs](https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging))
